previews:
  generation: automatic

services:
  - type: web
    name: ultra-siglad-backend
    runtime: node          # <- OJO: 'runtime', no 'env'
    plan: starter
    branch: master
    numInstances: 2
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false

staticSites:
  - name: ultra-siglad-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: ultra-siglad-backend
          property: url
