previews:
  generation: automatic

services:
  - type: web
    name: ultra-siglad-backend
    runtime: node
    plan: starter
    branch: master
    numInstances: 2
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
